contactUs
hngi/HNGi8_BE pull request #43
Opened 2020-07-26 09:45 UTC by Zeeson

This is a contactUs logic. 
Please review for update

2020-07-26 12:20 UTC, timothymayor commented
Hello bro... there are merge conflicts in your PR! please, sort it out and submit again

2020-07-27 11:27 UTC, tonymj76 requested changes

2020-07-27 11:27 UTC, tonymj76 commented on models/Mentor.js
> +const Schema = mongoose.Schema
please leave this line the way it was

2020-07-27 11:27 UTC, tonymj76 commented on models/Mentor.js
> +const MentorLogin = mongoose.model("MentorLogin", mentorLoginSchema);
what is the difference with the one you changed

2020-07-27 11:58 UTC, closed without merging